use crate::config::Config;
use crate::dns::hosts::DynamicHosts;
use crate::dns::router::Router;
use crate::firewall::FirewallGuard;
use anyhow::{Context, Result};
use clap::Parser;
use std::path::PathBuf;
use std::sync::Arc;
use tracing::{info, warn};

const RESOLV_CONF:     &str = "/etc/resolv.conf";
const RESOLV_CONF_BAK: &str = "/etc/resolv.conf.dnsroxy.bak";

#[derive(Parser, Debug)]
pub struct RunArgs {
    #[arg(short, long, default_value = "/etc/omnidns/config.yaml")]
    pub config: PathBuf,
}

pub async fn run(args: RunArgs) -> Result<()> {
    let config = Config::load(&args.config)
        .with_context(|| format!("Failed to load config from {}", args.config.display()))?;

    // 根据配置文件 log-level 重新初始化日志（环境变量 RUST_LOG 优先）。
    crate::init_logging(config.log_level);

    info!("Starting omnidns on {}", config.listen);

    // Warn if plain UDP upstreams are used with firewall redirect
    if config.firewall.as_ref().map(|f| f.enable).unwrap_or(false) {
        let has_plain = config.groups.values()
            .any(|g| g.servers.iter().any(|s| s.starts_with("udp://")));
        if has_plain {
            warn!(
                "Firewall redirect enabled with UDP upstreams — \
                 this may cause routing loops. Use DoT/DoH upstreams instead."
            );
        }
    }

    // Firewall redirect
    let _firewall_guard = if let Some(ref fw) = config.firewall {
        if fw.enable {
            let port = config.listen.port();
            let uid  = unsafe { libc::getuid() };
            Some(FirewallGuard::setup(fw, port, uid)
                .context("Failed to set up firewall redirect")?)
        } else { None }
    } else { None };

    // resolv.conf management
    let _resolv_guard = if config.manage_resolv_conf {
        Some(ResolvConfGuard::install()?)
    } else { None };

    // Shared dynamic hosts (populated by DHCP leases)
    let dhcp_domain = config.dhcp
        .v4.as_ref().and_then(|v| v.domain.clone())
        .or_else(|| config.dhcp.v6.as_ref().and_then(|v| v.domain.clone()));
    let dynamic_hosts = Arc::new(DynamicHosts::new(dhcp_domain));

    // Build DNS router
    let router = Arc::new(
        Router::from_config(&config, dynamic_hosts.clone())
            .context("Failed to build DNS router")?
    );

    // Shutdown channel
    let (shutdown_tx, mut shutdown_rx) = tokio::sync::oneshot::channel::<()>();
    tokio::spawn(async move {
        wait_for_signal().await;
        let _ = shutdown_tx.send(());
    });

    // Start DNS server
    let listen_addr = config.listen;
    let dns_handle = tokio::spawn(async move {
        if let Err(e) = crate::dns::serve(listen_addr, router).await {
            tracing::error!("DNS server error: {}", e);
        }
    });

    // Start DHCP/RA if configured
    let dhcp_cfg = config.dhcp.clone();
    let dhcp_hosts = dynamic_hosts.clone();
    let dhcp_handle = tokio::spawn(async move {
        if let Err(e) = crate::dhcp::serve(dhcp_cfg, dhcp_hosts).await {
            tracing::error!("DHCP/RA error: {}", e);
        }
    });

    info!("omnidns running. Press Ctrl+C to stop.");

    tokio::select! {
        _ = &mut shutdown_rx => { info!("Shutdown signal received"); }
        _ = dns_handle  => { info!("DNS server exited"); }
        _ = dhcp_handle => { info!("DHCP/RA exited"); }
    }

    info!("Shutting down...");
    Ok(())
}

async fn wait_for_signal() {
    use tokio::signal::unix::{signal, SignalKind};
    let mut sigterm = signal(SignalKind::terminate()).expect("SIGTERM handler");
    let mut sigint  = signal(SignalKind::interrupt()).expect("SIGINT handler");
    tokio::select! {
        _ = sigterm.recv() => { info!("SIGTERM"); }
        _ = sigint.recv()  => { info!("SIGINT"); }
    }
}

struct ResolvConfGuard;

impl ResolvConfGuard {
    fn install() -> Result<Self> {
        if std::path::Path::new(RESOLV_CONF_BAK).exists() {
            warn!("Backup {} already exists (previous unclean shutdown?)", RESOLV_CONF_BAK);
        }
        if std::path::Path::new(RESOLV_CONF).exists() {
            std::fs::copy(RESOLV_CONF, RESOLV_CONF_BAK)
                .context("Failed to backup /etc/resolv.conf")?;
            info!("Backed up {} → {}", RESOLV_CONF, RESOLV_CONF_BAK);
        }
        std::fs::write(RESOLV_CONF,
            "# Generated by omnidns\n\
             # Original backed up at /etc/resolv.conf.dnsroxy.bak\n\
             nameserver 127.0.0.1\n")
            .context("Failed to write /etc/resolv.conf")?;
        info!("Wrote {}", RESOLV_CONF);
        Ok(Self)
    }
}

impl Drop for ResolvConfGuard {
    fn drop(&mut self) {
        if std::path::Path::new(RESOLV_CONF_BAK).exists() {
            match std::fs::copy(RESOLV_CONF_BAK, RESOLV_CONF) {
                Ok(_) => {
                    let _ = std::fs::remove_file(RESOLV_CONF_BAK);
                    info!("Restored {}", RESOLV_CONF);
                }
                Err(e) => tracing::error!("Failed to restore {}: {}", RESOLV_CONF, e),
            }
        }
    }
}
